// Mocks generated by Mockito 5.3.2 from annotations
// in money_manager/test/application/usecases/add_transaction_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:money_manager/domain/factory/IEntityFactory.dart' as _i6;
import 'package:money_manager/domain/models/transaction_model.dart' as _i2;
import 'package:money_manager/domain/repositories/ITransactionRepository.dart'
    as _i4;
import 'package:money_manager/domain/value_objects/transaction/value_objects.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIncome_0 extends _i1.SmartFake implements _i2.Income {
  _FakeIncome_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExpense_1 extends _i1.SmartFake implements _i2.Expense {
  _FakeExpense_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmount_2 extends _i1.SmartFake implements _i3.Amount {
  _FakeAmount_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_3 extends _i1.SmartFake implements _i3.Category {
  _FakeCategory_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.ITransactionRepository {
  @override
  _i5.Future<void> add(_i2.Transaction? transactions) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [transactions],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i2.Transaction>> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
      ) as _i5.Future<List<_i2.Transaction>>);
}

/// A class which mocks [IEntityFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntityFactory extends _i1.Mock implements _i6.IEntityFactory {
  @override
  _i2.Income newIncome({
    required _i3.Amount? amount,
    _i3.Note? note,
    required _i3.Category? category,
    required DateTime? dateTime,
    required bool? recurring,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newIncome,
          [],
          {
            #amount: amount,
            #note: note,
            #category: category,
            #dateTime: dateTime,
            #recurring: recurring,
          },
        ),
        returnValue: _FakeIncome_0(
          this,
          Invocation.method(
            #newIncome,
            [],
            {
              #amount: amount,
              #note: note,
              #category: category,
              #dateTime: dateTime,
              #recurring: recurring,
            },
          ),
        ),
        returnValueForMissingStub: _FakeIncome_0(
          this,
          Invocation.method(
            #newIncome,
            [],
            {
              #amount: amount,
              #note: note,
              #category: category,
              #dateTime: dateTime,
              #recurring: recurring,
            },
          ),
        ),
      ) as _i2.Income);
  @override
  _i2.Expense newExpense({
    required _i3.Amount? amount,
    _i3.Note? note,
    required _i3.Category? category,
    required DateTime? dateTime,
    required bool? recurring,
    required String? medium,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newExpense,
          [],
          {
            #amount: amount,
            #note: note,
            #category: category,
            #dateTime: dateTime,
            #recurring: recurring,
            #medium: medium,
          },
        ),
        returnValue: _FakeExpense_1(
          this,
          Invocation.method(
            #newExpense,
            [],
            {
              #amount: amount,
              #note: note,
              #category: category,
              #dateTime: dateTime,
              #recurring: recurring,
              #medium: medium,
            },
          ),
        ),
        returnValueForMissingStub: _FakeExpense_1(
          this,
          Invocation.method(
            #newExpense,
            [],
            {
              #amount: amount,
              #note: note,
              #category: category,
              #dateTime: dateTime,
              #recurring: recurring,
              #medium: medium,
            },
          ),
        ),
      ) as _i2.Expense);
}

/// A class which mocks [Expense].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpense extends _i1.Mock implements _i2.Expense {
  @override
  String get medium => (super.noSuchMethod(
        Invocation.getter(#medium),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set medium(String? _medium) => super.noSuchMethod(
        Invocation.setter(
          #medium,
          _medium,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Amount get amount => (super.noSuchMethod(
        Invocation.getter(#amount),
        returnValue: _FakeAmount_2(
          this,
          Invocation.getter(#amount),
        ),
        returnValueForMissingStub: _FakeAmount_2(
          this,
          Invocation.getter(#amount),
        ),
      ) as _i3.Amount);
  @override
  set amount(_i3.Amount? _amount) => super.noSuchMethod(
        Invocation.setter(
          #amount,
          _amount,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Category get category => (super.noSuchMethod(
        Invocation.getter(#category),
        returnValue: _FakeCategory_3(
          this,
          Invocation.getter(#category),
        ),
        returnValueForMissingStub: _FakeCategory_3(
          this,
          Invocation.getter(#category),
        ),
      ) as _i3.Category);
  @override
  set category(_i3.Category? _category) => super.noSuchMethod(
        Invocation.setter(
          #category,
          _category,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set note(_i3.Note? _note) => super.noSuchMethod(
        Invocation.setter(
          #note,
          _note,
        ),
        returnValueForMissingStub: null,
      );
  @override
  DateTime get dateTime => (super.noSuchMethod(
        Invocation.getter(#dateTime),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.getter(#dateTime),
        ),
        returnValueForMissingStub: _FakeDateTime_4(
          this,
          Invocation.getter(#dateTime),
        ),
      ) as DateTime);
  @override
  set dateTime(DateTime? _dateTime) => super.noSuchMethod(
        Invocation.setter(
          #dateTime,
          _dateTime,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get recurring => (super.noSuchMethod(
        Invocation.getter(#recurring),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set recurring(bool? _recurring) => super.noSuchMethod(
        Invocation.setter(
          #recurring,
          _recurring,
        ),
        returnValueForMissingStub: null,
      );
}
